# netlify.toml

# Base build settings
[build]
  command = "bun run build"
  publish = ".next" # Or "dist" if using Vite

# Redirects and Rewrites
[[redirects]]
  # This is the crucial part for Single Page Applications (SPAs) like React.
  # It ensures that any request not matching an actual file in your 'publish' directory
  # (like /about, /projects, etc., that React Router handles)
  # is redirected to your main index.html file.
  from = "/*"
  to = "/index.html"
  status = 200 # This makes it a "rewrite" - the URL in the browser doesn't change.

[[plugins]]
package = "@netlify/plugin-nextjs"

# You can also add custom headers here if needed
# [[headers]]
#   for = "/*"
#   [headers.values]
#     X-Frame-Options = "DENY"
#     X-XSS-Protection = "1; mode=block"
#     Content-Security-Policy = "..."
